modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/aksource/NameWakander/issues" #optional
displayURL="https://github.com/aksource/NameWakander" #optional
#logoFile="examplemod.png" #optional
credits="Thanks for Minecraft Forge developers" #optional
authors="A.K." #optional
[[mods]] #mandatory
modId="name-wakander" #mandatory
version="1.14.4-1.3.8" #mandatory
displayName="NameWakander" #mandatory
updateJSONURL="https://raw.githubusercontent.com/aksource/NameWakander/master/update.json" #optional
description='''
This mod get registered objects in minecraft and write it in text files.
'''